# One should also update osdk/src/commands/new/rust-toolchain.toml.template
# when updating this
[toolchain]
channel = "nightly-2025-02-01"
components = ["rust-src", "rustc-dev", "llvm-tools-preview"]
targets = ["riscv64gc-unknown-none-elf"]