[build]
# 1. 裸机目标三元组
target = "riscv64gc-unknown-none-elf"
# 2. 传给 rustc/clippy 的额外 flag：打开 ktest cfg
rustflags = [
    "--check-cfg", "cfg(ktest)",
    "--cfg", "ktest",
]

[env]
# 透传给 rustc/clippy 的 RUSTFLAGS：开启 ktest cfg
RUSTFLAGS = "--check-cfg cfg(ktest) --cfg ktest"

[unstable]
# nightly 下的 -Zbuild-std 相关选项
# 把 core、alloc、compiler_builtins 三个库也用 build-std 编译
build-std = ["core", "alloc", "compiler_builtins"]
# 给 compiler_builtins 启用内存相关特性
build-std-features = ["compiler-builtins-mem"]
# .cargo/config.toml
