[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/asterinas/inherit-methods-macro?rev=98f7e3e"]
git = "https://github.com/asterinas/inherit-methods-macro"
rev = "98f7e3e"
replace-with = "vendored-sources"

[source."git+https://github.com/asterinas/ostd-pod?rev=c4644be"]
git = "https://github.com/asterinas/ostd-pod"
rev = "c4644be"
replace-with = "vendored-sources"

[source."git+https://github.com/asterinas/xarray"]
git = "https://github.com/asterinas/xarray"
replace-with = "vendored-sources"

[source."git+https://github.com/oscomp/arceos.git"]
git = "https://github.com/oscomp/arceos.git"
replace-with = "vendored-sources"

[source."git+https://github.com/tokio-rs/tracing"]
git = "https://github.com/tokio-rs/tracing"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"