name: Vsock Interaction

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vsock-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Run Vsock Server on Host
        id: host_vsock_server
        run: |
            sudo modprobe vhost_vsock
            sudo apt-get install socat
            echo "Run vsock server on host...."
            socat -ddd VSOCK-LISTEN:1234,fork SYSTEM:'read cmd; result=\$(eval \"\$cmd\" 2>&1); echo \"\$result\"' &
      - name: Run Vsock Client on Guest
        id: guest_vsock_client_server
        run: |
            docker run  --privileged --network=host --device=/dev/kvm -v ./:/root/asterinas asterinas/asterinas:0.4.2 \
            make run AUTO_TEST=vsock ENABLE_KVM=0 SCHEME=microvm RELEASE_MODE=1 
    